#!/usr/bin/env python3
"""Regenerate SKILL.md from CLAUDE.md."""

from __future__ import annotations

from pathlib import Path

NOTICE = (
    "This file is generated from [`CLAUDE.md`](CLAUDE.md) by "
    "`python3 scripts/sync_skill.py`. Do not edit this file directly.\n\n"
)


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        return "", text
    marker = "\n---\n"
    end = text.find(marker, 4)
    if end == -1:
        return "", text
    end += len(marker)
    return text[:end], text[end:]


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    source = root / "CLAUDE.md"
    target = root / "SKILL.md"
    frontmatter, body = split_frontmatter(source.read_text())
    body = body.replace(
        "This is the canonical source-of-truth file for the skill.",
        "This file mirrors the canonical instructions in [`CLAUDE.md`](CLAUDE.md).",
        1,
    )
    body = body.replace("- Edit this file first.", "- Edit `CLAUDE.md` first.", 1)
    payload = f"{frontmatter}\n{NOTICE}{body.lstrip()}"
    target.write_text(payload)


if __name__ == "__main__":
    main()
